# Generated by Django 4.2.28 on 2026-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
