# Generated by Django 4.2.28 on 2026-03-11 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_data', '0002_hazard_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HazardVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='map_data.hazard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hazardvote',
            constraint=models.UniqueConstraint(fields=('user', 'hazard'), name='unique_hazard_vote'),
        ),
    ]
