# Generated by Django 4.2.28 on 2026-03-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0003_hazard_author_hazardvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialalert',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='officialalert',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialalert',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WebcamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='webcams/')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('hut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_snapshots', to='map_data.hut')),
            ],
        ),
    ]
