# Generated by Django 4.2.28 on 2026-03-12 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("map_data", "0004_officialalert_content_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hazard",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved_by_author", "Resolved by Author"),
                    ("auto_expired", "Auto Expired"),
                    ("flagged_for_review", "Flagged for Review"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="HazardFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(default="outdated", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hazard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="map_data.hazard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazard_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "hazard"), name="unique_hazard_flag"
                    )
                ],
            },
        ),
    ]
